# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tab_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWindow(object):
    def setupUi(self, TabWindow):
        TabWindow.setObjectName("TabWindow")
        TabWindow.resize(800, 780)
        self.centralwidget = QtWidgets.QWidget(TabWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.TabWidget.setGeometry(QtCore.QRect(0, 40, 801, 561))
        self.TabWidget.setObjectName("TabWidget")
        self.TabMain = QtWidgets.QWidget()
        self.TabMain.setObjectName("TabMain")
        self.main_labelGPG = QtWidgets.QLabel(self.TabMain)
        self.main_labelGPG.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.main_labelGPG.setObjectName("main_labelGPG")
        self.main_labelGPGversion = QtWidgets.QLabel(self.TabMain)
        self.main_labelGPGversion.setGeometry(QtCore.QRect(110, 20, 131, 21))
        self.main_labelGPGversion.setObjectName("main_labelGPGversion")
        self.main_labelHome = QtWidgets.QLabel(self.TabMain)
        self.main_labelHome.setGeometry(QtCore.QRect(20, 50, 111, 21))
        self.main_labelHome.setObjectName("main_labelHome")
        self.main_labelHomeDir = QtWidgets.QLabel(self.TabMain)
        self.main_labelHomeDir.setGeometry(QtCore.QRect(140, 50, 331, 21))
        self.main_labelHomeDir.setObjectName("main_labelHomeDir")
        self.main_buttonSelectHome = QtWidgets.QPushButton(self.TabMain)
        self.main_buttonSelectHome.setGeometry(QtCore.QRect(20, 80, 91, 25))
        self.main_buttonSelectHome.setObjectName("main_buttonSelectHome")
        self.TabWidget.addTab(self.TabMain, "")
        self.TabEncrypt = QtWidgets.QWidget()
        self.TabEncrypt.setObjectName("TabEncrypt")
        self.encrypt_textOutput = QtWidgets.QPlainTextEdit(self.TabEncrypt)
        self.encrypt_textOutput.setGeometry(QtCore.QRect(25, 330, 550, 170))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        self.encrypt_textOutput.setFont(font)
        self.encrypt_textOutput.setObjectName("encrypt_textOutput")
        self.encrypt_textInput = QtWidgets.QPlainTextEdit(self.TabEncrypt)
        self.encrypt_textInput.setGeometry(QtCore.QRect(25, 140, 550, 150))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        self.encrypt_textInput.setFont(font)
        self.encrypt_textInput.setObjectName("encrypt_textInput")
        self.encrypt_buttonRecipients = QtWidgets.QPushButton(self.TabEncrypt)
        self.encrypt_buttonRecipients.setGeometry(QtCore.QRect(25, 20, 131, 25))
        self.encrypt_buttonRecipients.setObjectName("encrypt_buttonRecipients")
        self.encrypt_buttonImport = QtWidgets.QPushButton(self.TabEncrypt)
        self.encrypt_buttonImport.setGeometry(QtCore.QRect(25, 110, 91, 25))
        self.encrypt_buttonImport.setObjectName("encrypt_buttonImport")
        self.encrypt_buttonEncrypt = QtWidgets.QPushButton(self.TabEncrypt)
        self.encrypt_buttonEncrypt.setGeometry(QtCore.QRect(25, 300, 83, 25))
        self.encrypt_buttonEncrypt.setObjectName("encrypt_buttonEncrypt")
        self.encrypt_buttonSave = QtWidgets.QPushButton(self.TabEncrypt)
        self.encrypt_buttonSave.setGeometry(QtCore.QRect(120, 300, 83, 25))
        self.encrypt_buttonSave.setObjectName("encrypt_buttonSave")
        self.encrypt_listRecipient = QtWidgets.QListWidget(self.TabEncrypt)
        self.encrypt_listRecipient.setGeometry(QtCore.QRect(25, 50, 500, 50))
        self.encrypt_listRecipient.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.encrypt_listRecipient.setObjectName("encrypt_listRecipient")
        self.TabWidget.addTab(self.TabEncrypt, "")
        self.TabDecrypt = QtWidgets.QWidget()
        self.TabDecrypt.setObjectName("TabDecrypt")
        self.decrypt_textOutput = QtWidgets.QPlainTextEdit(self.TabDecrypt)
        self.decrypt_textOutput.setGeometry(QtCore.QRect(25, 280, 550, 150))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        self.decrypt_textOutput.setFont(font)
        self.decrypt_textOutput.setObjectName("decrypt_textOutput")
        self.decrypt_textInput = QtWidgets.QPlainTextEdit(self.TabDecrypt)
        self.decrypt_textInput.setGeometry(QtCore.QRect(25, 60, 550, 150))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        self.decrypt_textInput.setFont(font)
        self.decrypt_textInput.setObjectName("decrypt_textInput")
        self.decrypt_buttonDecrypt = QtWidgets.QPushButton(self.TabDecrypt)
        self.decrypt_buttonDecrypt.setGeometry(QtCore.QRect(25, 240, 83, 25))
        self.decrypt_buttonDecrypt.setObjectName("decrypt_buttonDecrypt")
        self.decrypt_buttonSave = QtWidgets.QPushButton(self.TabDecrypt)
        self.decrypt_buttonSave.setGeometry(QtCore.QRect(120, 240, 83, 25))
        self.decrypt_buttonSave.setObjectName("decrypt_buttonSave")
        self.decrypt_buttonImport = QtWidgets.QPushButton(self.TabDecrypt)
        self.decrypt_buttonImport.setGeometry(QtCore.QRect(25, 20, 83, 25))
        self.decrypt_buttonImport.setObjectName("decrypt_buttonImport")
        self.TabWidget.addTab(self.TabDecrypt, "")
        self.TabSign = QtWidgets.QWidget()
        self.TabSign.setObjectName("TabSign")
        self.sign_buttonImport = QtWidgets.QPushButton(self.TabSign)
        self.sign_buttonImport.setGeometry(QtCore.QRect(25, 20, 83, 25))
        self.sign_buttonImport.setObjectName("sign_buttonImport")
        self.sign_buttonSign = QtWidgets.QPushButton(self.TabSign)
        self.sign_buttonSign.setGeometry(QtCore.QRect(25, 250, 83, 25))
        self.sign_buttonSign.setObjectName("sign_buttonSign")
        self.sign_buttonSave = QtWidgets.QPushButton(self.TabSign)
        self.sign_buttonSave.setGeometry(QtCore.QRect(120, 250, 83, 25))
        self.sign_buttonSave.setObjectName("sign_buttonSave")
        self.sign_textInput = QtWidgets.QPlainTextEdit(self.TabSign)
        self.sign_textInput.setGeometry(QtCore.QRect(25, 60, 550, 171))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        self.sign_textInput.setFont(font)
        self.sign_textInput.setObjectName("sign_textInput")
        self.sign_textOutput = QtWidgets.QPlainTextEdit(self.TabSign)
        self.sign_textOutput.setGeometry(QtCore.QRect(25, 290, 550, 211))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        self.sign_textOutput.setFont(font)
        self.sign_textOutput.setReadOnly(True)
        self.sign_textOutput.setObjectName("sign_textOutput")
        self.TabWidget.addTab(self.TabSign, "")
        self.TabVerify = QtWidgets.QWidget()
        self.TabVerify.setObjectName("TabVerify")
        self.verify_buttonImport = QtWidgets.QPushButton(self.TabVerify)
        self.verify_buttonImport.setGeometry(QtCore.QRect(25, 20, 83, 25))
        self.verify_buttonImport.setObjectName("verify_buttonImport")
        self.verify_buttonVerify = QtWidgets.QPushButton(self.TabVerify)
        self.verify_buttonVerify.setGeometry(QtCore.QRect(25, 270, 83, 25))
        self.verify_buttonVerify.setObjectName("verify_buttonVerify")
        self.verify_textOutput = QtWidgets.QPlainTextEdit(self.TabVerify)
        self.verify_textOutput.setGeometry(QtCore.QRect(25, 310, 550, 191))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        self.verify_textOutput.setFont(font)
        self.verify_textOutput.setReadOnly(True)
        self.verify_textOutput.setObjectName("verify_textOutput")
        self.verify_textInput = QtWidgets.QPlainTextEdit(self.TabVerify)
        self.verify_textInput.setGeometry(QtCore.QRect(25, 60, 550, 191))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        self.verify_textInput.setFont(font)
        self.verify_textInput.setObjectName("verify_textInput")
        self.verify_buttonSave = QtWidgets.QPushButton(self.TabVerify)
        self.verify_buttonSave.setGeometry(QtCore.QRect(120, 270, 83, 25))
        self.verify_buttonSave.setObjectName("verify_buttonSave")
        self.TabWidget.addTab(self.TabVerify, "")
        self.TabKeyring = QtWidgets.QWidget()
        self.TabKeyring.setObjectName("TabKeyring")
        self.keyring_buttonImport = QtWidgets.QPushButton(self.TabKeyring)
        self.keyring_buttonImport.setGeometry(QtCore.QRect(20, 220, 83, 25))
        self.keyring_buttonImport.setObjectName("keyring_buttonImport")
        self.keyring_buttonImportKey = QtWidgets.QPushButton(self.TabKeyring)
        self.keyring_buttonImportKey.setGeometry(QtCore.QRect(20, 390, 83, 25))
        self.keyring_buttonImportKey.setObjectName("keyring_buttonImportKey")
        self.keyring_textInput = QtWidgets.QPlainTextEdit(self.TabKeyring)
        self.keyring_textInput.setGeometry(QtCore.QRect(20, 260, 501, 121))
        font = QtGui.QFont()
        font.setFamily("Fira Mono")
        self.keyring_textInput.setFont(font)
        self.keyring_textInput.setObjectName("keyring_textInput")
        self.keyring_labelPublicKey = QtWidgets.QLabel(self.TabKeyring)
        self.keyring_labelPublicKey.setGeometry(QtCore.QRect(20, 190, 131, 17))
        self.keyring_labelPublicKey.setObjectName("keyring_labelPublicKey")
        self.keyring_buttonSelectKeyring = QtWidgets.QPushButton(self.TabKeyring)
        self.keyring_buttonSelectKeyring.setGeometry(QtCore.QRect(20, 50, 121, 25))
        self.keyring_buttonSelectKeyring.setObjectName("keyring_buttonSelectKeyring")
        self.keyring_labelCurrentKey = QtWidgets.QLabel(self.TabKeyring)
        self.keyring_labelCurrentKey.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.keyring_labelCurrentKey.setObjectName("keyring_labelCurrentKey")
        self.keyring_labelCurrentKeyPath = QtWidgets.QLabel(self.TabKeyring)
        self.keyring_labelCurrentKeyPath.setGeometry(QtCore.QRect(130, 20, 411, 16))
        self.keyring_labelCurrentKeyPath.setObjectName("keyring_labelCurrentKeyPath")
        self.TabWidget.addTab(self.TabKeyring, "")
        self.combo_currentKey = QtWidgets.QComboBox(self.centralwidget)
        self.combo_currentKey.setGeometry(QtCore.QRect(90, 10, 591, 21))
        self.combo_currentKey.setObjectName("combo_currentKey")
        self.label_currentKey = QtWidgets.QLabel(self.centralwidget)
        self.label_currentKey.setGeometry(QtCore.QRect(10, 10, 77, 21))
        self.label_currentKey.setObjectName("label_currentKey")
        self.text_logOutput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_logOutput.setGeometry(QtCore.QRect(25, 640, 750, 90))
        self.text_logOutput.setObjectName("text_logOutput")
        self.label_logOutput = QtWidgets.QLabel(self.centralwidget)
        self.label_logOutput.setGeometry(QtCore.QRect(30, 610, 81, 17))
        self.label_logOutput.setObjectName("label_logOutput")
        TabWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TabWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        TabWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TabWindow)
        self.statusbar.setObjectName("statusbar")
        TabWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(TabWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(TabWindow)
        self.TabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(TabWindow)

    def retranslateUi(self, TabWindow):
        _translate = QtCore.QCoreApplication.translate
        TabWindow.setWindowTitle(_translate("TabWindow", "gGPG"))
        self.main_labelGPG.setText(_translate("TabWindow", "GPG Version"))
        self.main_labelGPGversion.setText(_translate("TabWindow", "None"))
        self.main_labelHome.setText(_translate("TabWindow", "Home Directory:"))
        self.main_labelHomeDir.setText(_translate("TabWindow", "None"))
        self.main_buttonSelectHome.setText(_translate("TabWindow", "Select Home"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabMain), _translate("TabWindow", "Main"))
        self.encrypt_buttonRecipients.setText(_translate("TabWindow", "Select Recipients"))
        self.encrypt_buttonImport.setText(_translate("TabWindow", "Import File"))
        self.encrypt_buttonEncrypt.setText(_translate("TabWindow", "Encrypt"))
        self.encrypt_buttonSave.setText(_translate("TabWindow", "Save"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabEncrypt), _translate("TabWindow", "Encrypt"))
        self.decrypt_buttonDecrypt.setText(_translate("TabWindow", "Decrypt"))
        self.decrypt_buttonSave.setText(_translate("TabWindow", "Save"))
        self.decrypt_buttonImport.setText(_translate("TabWindow", "Import File"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabDecrypt), _translate("TabWindow", "Decrypt"))
        self.sign_buttonImport.setText(_translate("TabWindow", "Import File"))
        self.sign_buttonSign.setText(_translate("TabWindow", "Sign"))
        self.sign_buttonSave.setText(_translate("TabWindow", "Save"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabSign), _translate("TabWindow", "Sign"))
        self.verify_buttonImport.setText(_translate("TabWindow", "Import"))
        self.verify_buttonVerify.setText(_translate("TabWindow", "Verify"))
        self.verify_buttonSave.setText(_translate("TabWindow", "Save"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabVerify), _translate("TabWindow", "Verify"))
        self.keyring_buttonImport.setText(_translate("TabWindow", "Import FIle"))
        self.keyring_buttonImportKey.setText(_translate("TabWindow", "Import Key"))
        self.keyring_labelPublicKey.setText(_translate("TabWindow", "Import Public Key"))
        self.keyring_buttonSelectKeyring.setText(_translate("TabWindow", "Select Keyring"))
        self.keyring_labelCurrentKey.setText(_translate("TabWindow", "Current Keyring:"))
        self.keyring_labelCurrentKeyPath.setText(_translate("TabWindow", "Default"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.TabKeyring), _translate("TabWindow", "Keyring"))
        self.label_currentKey.setText(_translate("TabWindow", "Current Key"))
        self.label_logOutput.setText(_translate("TabWindow", "Output Log"))
        self.menuFile.setTitle(_translate("TabWindow", "File"))
        self.actionQuit.setText(_translate("TabWindow", "Quit"))
